graph TD
    %% TODO: Complete this diagram to match your DAG
    %% 
    %% Instructions:
    %% 1. Add all tasks as nodes
    %% 2. Add arrows showing dependencies
    %% 3. Use subgraphs to show parallel tasks
    %% 4. Mark the branching decision point
    
    START[start]
    
    %% TODO: Add extraction tasks
    %% Example: EXT_US[extract_us]
    
    
    %% TODO: Add aggregation task
    
    
    %% TODO: Add branching
    %% Example: BRANCH{choose_path}
    
    
    %% TODO: Add processing paths
    
    
    %% TODO: Add join, cleanup, end
    
    
    %% TODO: Add dependency arrows
    %% Example: START --> EXT_US
