// =============================================================================
// M Language Reference — Power Query Examples
// For: Monday Demo 3 - Power Query Basics
// Note: M code is auto-generated by Power Query. This file is a reference.
// =============================================================================

// -----------------------------------------------------------------------------
// EXAMPLE 1: Basic Snowflake Connection + Transformations
// -----------------------------------------------------------------------------
// This is what Power Query generates when you connect to Snowflake and apply
// transformations through the UI (rename, filter, add column).

let
    // Step 1: Connect to Snowflake
    Source = Snowflake.Databases("account.snowflakecomputing.com", "COMPUTE_WH"),

    // Step 2: Navigate to database
    DEV_DB_Database = Source{[Name="DEV_DB"]}[Data],

    // Step 3: Navigate to schema
    GOLD_Schema = DEV_DB_Database{[Name="GOLD"]}[Data],

    // Step 4: Select table
    DIM_CUSTOMER_Table = GOLD_Schema{[Name="DIM_CUSTOMER"]}[Data],

    // Step 5: Rename column (human-friendly names)
    #"Renamed Columns" = Table.RenameColumns(
        DIM_CUSTOMER_Table,
        {{"CUSTOMER_NAME", "Customer Name"}}
    ),

    // Step 6: Change data type
    #"Changed Type" = Table.TransformColumnTypes(
        #"Renamed Columns",
        {{"Customer Name", type text}, {"customer_key", Int64.Type}}
    )
in
    #"Changed Type"


// -----------------------------------------------------------------------------
// EXAMPLE 2: Filtering and Adding Custom Column
// -----------------------------------------------------------------------------

let
    Source = Snowflake.Databases("account.snowflakecomputing.com", "COMPUTE_WH"),
    DEV_DB = Source{[Name="DEV_DB"]}[Data],
    GOLD = DEV_DB{[Name="GOLD"]}[Data],
    FCT = GOLD{[Name="FCT_ORDER_LINES"]}[Data],

    // Filter out cancelled orders
    #"Filtered Rows" = Table.SelectRows(
        FCT,
        each ([ORDER_STATUS] <> "Cancelled")
    ),

    // Add calculated column: Net Amount
    #"Added Custom" = Table.AddColumn(
        #"Filtered Rows",
        "Net Amount",
        each [EXTENDED_PRICE] * (1 - [DISCOUNT_PCT]),
        type number
    )
in
    #"Added Custom"


// -----------------------------------------------------------------------------
// KEY M LANGUAGE CONCEPTS
// -----------------------------------------------------------------------------
//
// 1. M is FUNCTIONAL — each step is a variable referencing the previous step
// 2. let...in structure: "let" defines steps, "in" returns the final result
// 3. Table.* functions: RenameColumns, SelectRows, AddColumn, TransformColumnTypes
// 4. #"Name with spaces" syntax: Use quotes for step names with special characters
// 5. "each" keyword: Shorthand for (_) => _ (anonymous function over current row)
//
// TIP: You rarely need to write M manually. Use the Power Query UI and then
// review the Advanced Editor to understand what was generated.
